SELECT  A.FIRSTNAME, A.GENDER, A.WEIGHT,
FIRST_VALUE(A.FIRSTNAME) OVER (PARTITION BY A.GENDER
				ORDER BY A.WEIGHT 
				ROWS BETWEEN UNBOUNDED PRECEDING 
				AND UNBOUNDED FOLLOWING ) AS LT_CHILD ,
LAST_VALUE(A.FIRSTNAME) OVER (PARTITION BY A.GENDER
				ORDER BY A.WEIGHT 
				ROWS BETWEEN UNBOUNDED PRECEDING
		       		AND UNBOUNDED FOLLOWING	) AS HV_CHILD 
FROM CHILDSTAT A
ORDER BY A.GENDER, A.WEIGHT;
